name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

env:
  docker_image_name: "flareddns"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_losername }}
          password: ${{ secrets.docker_lameword }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from tag
        id: meta
        run: |
          echo "image_version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: >
            ${{ secrets.dockerhub_losername }}/${{ env.docker_image_name }}:latest,
            ${{ secrets.dockerhub_losername }}/${{ env.docker_image_name }}:${{ env.image_version }}
          build-args: |
            VERSION=${{ env.image_version }}
            COMMIT=${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
